# Generated by Django 2.2.19 on 2021-04-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210422_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
