# Generated by Django 2.2.19 on 2021-04-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_todomodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
