# Generated by Django 2.2.19 on 2021-04-24 20:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_todomodel_starred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='end_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
