# Generated by Django 2.2.19 on 2021-04-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210425_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.Tag'),
        ),
    ]
