# Generated by Django 3.1.7 on 2021-05-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210516_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
